export enum IconsEnum {
    LOGO = 'logo',
    LAMBDA_LEFT = 'lambda-left',
    LAMBDA_RIGHT = 'lambda-right',
    DISCUSSION = 'discussion',
    PANDORAS_BOX = 'pandoras-box',
    HEADER_ORNAMENT = 'header-ornament',
    SECTION_ORNAMENT_LEFT = 'section-ornament-left',
    SECTION_ORNAMENT_RIGHT = 'section-ornament-right',
    YOUTUBE = 'youtube',
    INSTAGRAM = 'instagram',
    FACEBOOK = 'facebook',
    TELEGRAM = 'telegram',
    APPLE_PODCASTS = 'apple-podcasts',
    SOUNDCLOUD = 'soundcloud',
    POCKET_CASTS = 'pocket-casts',
    GOOGLE_PODCASTS = 'google-podcasts',
    SPOTIFY = 'spotify',
    CIRCLES = 'circles',
    VISIBLE = 'visible',
    INVISIBLE = 'invisible',
}
