export enum RoutesEnum {
    ROOT = '',
    LANDING = 'landing',
    SIGN_IN = 'sign-in',
    SIGN_UP = 'sign-up',
    FORGOT_PASSWORD = 'forgot-password',
    RESET_PASSWORD = 'reset-password',
    VERIFICATION = 'verification',
    NOT_FOUND = 'not-found',
    DASHBOARD = 'dashboard',
    SHOW = 'show',
    SHOW_CREATE = 'show/create/new',
    SHOW_EDIT = 'show/edit',
    EPISODE = 'episode',
}
